const buttonBase =
  'inline-flex min-h-12 items-center justify-center rounded-xl px-5 py-3 text-center text-sm font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2';

export const pageStyles = {
  page: 'min-h-screen bg-background py-8 text-foreground sm:py-12',
  main: 'min-h-screen bg-background py-8 text-foreground sm:py-12',
  container: 'mx-auto w-full max-w-[1200px] px-4 sm:px-6',
  hero: 'relative mb-8 overflow-hidden rounded-[28px] border border-line bg-surface p-6 shadow-soft sm:p-10 lg:p-14',
  header: 'mb-8 rounded-[28px] border border-line bg-surface p-6 shadow-soft sm:p-10',
  eyebrow: 'mb-3 text-xs font-black tracking-[0.16em] text-brand uppercase',
  badge: 'mb-4 inline-flex rounded-full border border-red-300/30 bg-brand-soft px-3 py-1 text-xs font-bold tracking-wider text-brand uppercase',
  title: 'text-[clamp(2rem,5vw,4rem)] font-black leading-[1.04] tracking-[-0.045em] text-foreground text-balance',
  subtitle: 'mt-4 max-w-3xl text-base leading-relaxed text-muted sm:text-lg',
  lead: 'text-lg leading-relaxed text-muted',
  meta: 'mt-4 flex flex-wrap gap-3 text-sm text-muted',
  section: 'mb-8 rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-8',
  block: 'mb-8 rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-8',
  article: 'mx-auto max-w-4xl rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-10 [&_h2]:mb-4 [&_h2]:mt-10 [&_h2]:text-2xl [&_h2]:font-black [&_p]:mb-5 [&_p]:leading-8 [&_p]:text-muted [&_ul]:mb-5 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6',
  sectionTitle: 'mb-4 text-[clamp(1.5rem,3vw,2.25rem)] font-black tracking-tight text-foreground',
  blockTitle: 'mb-4 text-[clamp(1.4rem,2.5vw,2rem)] font-black tracking-tight text-foreground',
  ctaTitle: 'mb-4 text-2xl font-black tracking-tight text-foreground',
  text: 'leading-7 text-muted',
  sectionText: 'leading-7 text-muted',
  grid: 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3',
  benefitsGrid: 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3',
  card: 'rounded-2xl border border-line bg-surface-raised p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-red-300/50 hover:shadow-card dark:hover:border-red-500/40',
  cardTitle: 'mb-3 text-lg font-extrabold text-foreground',
  infoList: 'grid gap-3 text-muted [&_strong]:text-foreground',
  list: 'grid gap-3 text-muted [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:text-brand [&_li]:before:content-["✓"]',
  steps: 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3',
  links: 'mt-5 flex flex-wrap gap-3',
  actions: 'mt-6 flex flex-wrap gap-3',
  primaryBtn: `${buttonBase} bg-brand-solid text-white shadow-lg shadow-red-950/15 hover:-translate-y-0.5 hover:bg-brand-solid-strong focus-visible:outline-brand`,
  secondaryBtn: `${buttonBase} border border-line bg-surface-raised text-foreground hover:-translate-y-0.5 hover:border-red-300/60 hover:bg-brand-soft focus-visible:outline-brand`,
  primary: `${buttonBase} bg-brand-solid text-white shadow-lg shadow-red-950/15 hover:-translate-y-0.5 hover:bg-brand-solid-strong focus-visible:outline-brand`,
  secondary: `${buttonBase} border border-line bg-surface-raised text-foreground hover:-translate-y-0.5 hover:border-red-300/60 hover:bg-brand-soft focus-visible:outline-brand`,
  linkBtn: `${buttonBase} border border-line bg-surface-raised text-foreground hover:border-red-300/60 hover:bg-brand-soft`,
  linkBtnPrimary: `${buttonBase} bg-brand-solid text-white hover:bg-brand-solid-strong`,
  cta: 'mt-8 rounded-3xl border border-red-300/25 bg-brand-soft p-6 sm:p-8',
  faq: 'grid gap-4',
  disclaimer: 'mt-6 rounded-2xl border border-amber-400/30 bg-amber-50 p-4 text-sm leading-relaxed text-amber-950 dark:bg-amber-950/25 dark:text-amber-100',
  noticeBlock: 'mb-6 rounded-2xl border border-amber-400/30 bg-amber-50 p-5 dark:bg-amber-950/25',
  noticeTitle: 'mb-2 text-lg font-black text-amber-950 dark:text-amber-100',
  noticeText: 'leading-7 text-amber-900 dark:text-amber-200',
  lastUpdated: 'mt-3 text-sm text-muted',
  email: 'font-bold text-brand underline underline-offset-4',
  full: 'sm:col-span-2 lg:col-span-3',
  formWrap: 'rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-8',
  emailRow: 'flex flex-wrap items-center gap-2 text-muted',
  officeAddress: 'leading-7 text-muted',
  mapLink: 'mt-4 inline-flex min-h-11 items-center font-bold text-brand underline underline-offset-4',
  mapWrap: 'mt-5 overflow-hidden rounded-2xl border border-line',
  mapFrame: 'h-[360px] w-full border-0',
  reviewBox: 'mt-6 rounded-2xl border border-red-300/30 bg-brand-soft p-4 text-sm leading-6 text-muted [&_strong]:mb-1 [&_strong]:block [&_strong]:text-foreground',
  stepNumber: 'mb-3 block text-3xl font-black text-brand',
  sourceList: 'grid gap-3 [&_a]:font-bold [&_a]:text-brand [&_a]:underline [&_a]:underline-offset-4',
  relatedLinks: 'mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3',
  relatedLink: 'flex min-h-14 items-center justify-between gap-3 rounded-2xl border border-line bg-surface-raised px-4 py-3 font-extrabold text-foreground transition hover:-translate-y-0.5 hover:border-red-300/60 hover:bg-brand-soft hover:text-brand focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand',
};

export const homeStyles = {
  page: 'bg-background text-foreground',
  main: 'mx-auto w-full max-w-[1500px] px-3 pb-16 pt-5 sm:px-5 sm:pt-8',
  formContainer: 'mx-auto grid max-w-[1400px] grid-cols-[minmax(120px,260px)_1fr] items-center gap-5 rounded-[32px] bg-[#09090b] p-4 shadow-2xl shadow-red-950/20 max-md:grid-cols-1 max-md:rounded-3xl',
  logoImage: 'mx-auto aspect-square w-full max-w-[240px] rounded-3xl object-cover max-md:max-w-[130px]',
  seoSection: 'mx-auto max-w-[1400px] px-2 py-12 sm:px-5 sm:py-20',
  seoIntro: 'mb-6 rounded-3xl border border-line bg-surface p-6 shadow-soft sm:p-9',
  seoGrid: 'grid grid-cols-2 gap-4 max-md:grid-cols-1',
  seoCard: 'rounded-3xl border border-line bg-surface p-6 shadow-soft transition hover:-translate-y-0.5 hover:border-red-300/50 hover:shadow-card sm:p-8 dark:hover:border-red-500/40',
  seoCardWide: 'col-span-full',
  seoEyebrow: 'mb-3 text-xs font-black tracking-[0.16em] text-brand uppercase',
  seoTitle: 'mb-4 text-[clamp(1.5rem,3vw,2.45rem)] font-black tracking-tight text-foreground',
  seoText: 'mb-4 leading-7 text-muted',
  seoList: 'grid gap-3 text-muted sm:grid-cols-2 [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:text-brand [&_li]:before:content-["✓"]',
  seoLinks: 'mt-6 flex flex-wrap gap-3',
  seoLinkPrimary: `${buttonBase} bg-brand-solid text-white hover:bg-brand-solid-strong`,
  seoLinkSecondary: `${buttonBase} border border-line bg-surface-raised text-foreground hover:bg-brand-soft`,
  prioritySection: 'mx-auto max-w-[1400px] px-2 py-12 sm:px-5 sm:py-20',
  priorityHeader: 'mb-6 max-w-4xl',
  priorityGrid: 'grid gap-4 md:grid-cols-2',
  priorityCardTitle: 'mb-3 text-xl font-black tracking-tight text-foreground sm:text-2xl',
  priorityLinks: 'grid gap-2 [&_a]:font-bold [&_a]:text-brand [&_a]:underline-offset-4 [&_a:hover]:underline',
  cityLinks: 'mt-5 rounded-3xl border border-line bg-surface p-6 shadow-soft sm:p-8',
  cityLinkList: 'mt-5 flex flex-wrap gap-3',
  faqSection: 'mx-auto max-w-[1400px] px-2 py-12 sm:px-5 sm:py-20',
  faqHeader: 'mb-6',
  faqGrid: 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3',
  faqCard: 'rounded-2xl border border-line bg-surface p-5 shadow-sm',
  faqQuestion: 'mb-3 text-lg font-extrabold text-foreground',
  faqAnswer: 'leading-7 text-muted',
  reviewsSection: 'mx-auto max-w-[1400px] px-2 py-12 sm:px-5 sm:py-20',
  reviewsHeader: 'mb-6 flex items-end justify-between gap-4 max-sm:flex-col max-sm:items-start',
  reviewsGrid: 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3',
  reviewCard: 'flex min-h-48 flex-col rounded-2xl border border-line bg-surface p-5 shadow-soft',
  reviewStars: 'mb-3 text-lg tracking-wider text-amber-400',
  reviewText: 'mb-5 flex-1 leading-7 text-muted',
  reviewAuthor: 'font-extrabold text-foreground',
  reviewsLink: `${buttonBase} border border-line bg-surface text-foreground hover:border-red-300/60 hover:bg-brand-soft`,
};

export const carGridStyles = {
  section: 'bg-background py-12 text-foreground sm:py-20',
  container: 'mx-auto max-w-[1400px] px-4 sm:px-6',
  title: 'text-[clamp(2rem,4vw,3.5rem)] font-black tracking-[-0.04em] text-foreground',
  description: 'mt-4 max-w-3xl leading-7 text-muted',
  grid: 'mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3',
  card: 'group flex h-full flex-col overflow-hidden rounded-3xl border border-line bg-surface shadow-soft transition duration-300 hover:-translate-y-1 hover:border-red-300/60 hover:shadow-card focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand dark:hover:border-red-500/50',
  imageContainer: 'relative aspect-[16/10] overflow-hidden bg-zinc-100 dark:bg-zinc-900',
  carImage: 'h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]',
  yearBadge: 'absolute left-4 top-4 rounded-full border border-white/20 bg-black/70 px-3 py-1 text-xs font-extrabold text-white shadow-lg backdrop-blur-md',
  cardContent: 'flex flex-1 flex-col p-5',
  cardHeader: 'flex items-start justify-between gap-3',
  carName: 'text-xl font-black tracking-tight text-foreground',
  cardArrow: 'mt-0.5 shrink-0 text-muted transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-brand',
  specGrid: 'mt-4 grid grid-cols-2 gap-2',
  specItem: 'flex min-w-0 items-center gap-2 rounded-xl bg-background px-3 py-2.5 text-brand [&_small]:block [&_small]:truncate [&_small]:text-[10px] [&_small]:font-bold [&_small]:tracking-wide [&_small]:text-muted [&_small]:uppercase [&_strong]:block [&_strong]:truncate [&_strong]:text-xs [&_strong]:text-foreground',
  categoryList: 'mt-4 flex min-h-7 flex-wrap gap-1.5',
  categoryTag: 'inline-flex items-center rounded-full border border-line bg-surface-raised px-2.5 py-1 text-[11px] font-bold text-muted',
  pricing: 'mt-4 grid grid-cols-2 gap-2 border-t border-line pt-4',
  priceBlock: 'min-w-0 [&_span]:block [&_span]:text-[10px] [&_span]:font-bold [&_span]:tracking-wide [&_span]:text-muted [&_span]:uppercase [&_strong]:mt-1 [&_strong]:block [&_strong]:truncate [&_strong]:text-sm [&_strong]:font-black [&_strong]:text-foreground',
  cardCta: 'mt-5 flex min-h-11 items-center justify-between rounded-xl bg-brand-soft px-3.5 text-sm font-extrabold text-brand transition group-hover:bg-brand-solid group-hover:text-white',
};

export const carouselStyles = {
  ...carGridStyles,
  sliderWrapper: 'relative mt-8',
  grid: 'flex snap-x snap-mandatory gap-5 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  carouselCard: 'min-w-[86%] snap-start sm:min-w-[46%] lg:min-w-[31%] xl:min-w-[24%]',
  navBtn: 'absolute top-1/2 z-10 hidden size-12 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-black/75 text-3xl text-white shadow-xl backdrop-blur transition hover:bg-brand-solid disabled:pointer-events-none disabled:opacity-30 sm:flex',
  prev: '-left-4',
  next: '-right-4',
  controls: 'mx-auto mt-5 flex w-full max-w-full justify-start gap-0.5 overflow-x-auto px-1 py-1 [scrollbar-width:none] sm:w-fit sm:justify-center sm:overflow-visible sm:rounded-full sm:border sm:border-line sm:bg-surface-raised sm:px-2 [&::-webkit-scrollbar]:hidden',
  dot: 'flex size-11 shrink-0 items-center justify-center rounded-full border-0 bg-transparent transition before:block before:h-2.5 before:w-2.5 before:rounded-full before:bg-zinc-400 before:transition-all before:content-[""] hover:before:bg-brand focus-visible:outline-2 focus-visible:outline-offset-[-4px] focus-visible:outline-brand',
  activeDot: 'before:w-7 before:bg-brand',
};

export const formStyles = {
  container: 'mx-auto my-12 max-w-4xl rounded-[30px] border border-line bg-surface p-5 text-foreground shadow-soft sm:p-9',
  mainTitle: 'text-[clamp(1.75rem,4vw,3rem)] font-black tracking-tight text-foreground',
  subTitle: 'mt-3 leading-7 text-muted',
  form: 'mt-7 grid gap-4 sm:grid-cols-2',
  fieldWrapper: 'min-w-0',
  inputField: 'h-13 w-full rounded-xl border border-line bg-background px-4 text-foreground outline-none transition placeholder:text-muted/70 focus:border-brand focus:ring-4 focus:ring-red-500/10',
  w3: '',
  org: '',
  consentContainer: 'flex items-start gap-3 sm:col-span-2',
  checkbox: 'mt-1 size-5 shrink-0 accent-brand',
  consentLabel: 'cursor-pointer',
  consentText: 'text-sm leading-6 text-muted',
  link: 'font-bold text-brand underline underline-offset-4',
  submitButton: 'min-h-13 rounded-xl bg-brand-solid px-6 font-extrabold text-white shadow-lg shadow-red-950/15 transition hover:-translate-y-0.5 hover:bg-brand-solid-strong sm:col-span-2',
  visuallyHidden: 'sr-only',
};

export const socialStyles = {
  wrapper: 'mx-auto my-12 max-w-[1400px] overflow-hidden rounded-[32px] border border-line bg-surface px-5 py-10 shadow-soft sm:px-10 sm:py-14',
  container: 'grid items-center gap-8 lg:grid-cols-[1.1fr_.9fr]',
  content: 'relative z-10',
  badge: 'mb-4 inline-flex rounded-full bg-brand-soft px-3 py-1 text-xs font-black tracking-wider text-brand uppercase',
  heading: 'text-[clamp(2rem,5vw,4rem)] font-black leading-[1.04] tracking-[-0.045em] text-foreground',
  text: 'mt-4 max-w-2xl leading-7 text-muted',
  buttonGroup: 'mt-7 flex flex-wrap gap-3',
  ctaButton: 'inline-flex min-h-12 items-center gap-2 rounded-xl border border-line bg-surface-raised px-4 font-bold text-foreground transition hover:-translate-y-0.5 hover:border-red-300/60 hover:bg-brand-soft',
  buttonText: 'text-sm',
  visuals: 'relative hidden min-h-72 items-center justify-center lg:flex',
  circle: 'absolute rounded-full blur-2xl',
  circle1: 'right-4 top-3 size-56 bg-red-500/20',
  circle2: 'bottom-0 left-6 size-44 bg-orange-400/15',
  glassCard: 'relative z-10 -rotate-3 rounded-3xl border border-white/20 bg-[#111114]/90 px-10 py-14 text-2xl font-black text-white shadow-2xl backdrop-blur-xl',
};

export const chatStyles = {
  wrapper: 'fixed bottom-[calc(18px+env(safe-area-inset-bottom))] right-4 z-[10000] max-w-[calc(100vw-32px)]',
  launcher: 'ml-auto inline-flex size-14 items-center justify-center rounded-full border border-white/20 bg-brand-solid text-white shadow-2xl shadow-red-950/35 transition hover:-translate-y-1 hover:bg-brand-solid-strong',
  chatWindow: 'mb-3 flex h-[min(620px,calc(100dvh-110px))] w-[min(390px,calc(100vw-32px))] flex-col overflow-hidden rounded-3xl border border-line bg-surface-raised text-foreground shadow-2xl',
  header: 'flex min-h-16 items-center justify-between border-b border-white/10 bg-[#111114] px-4 text-white',
  headerInfo: 'flex items-center gap-2.5',
  statusDot: 'size-2.5 rounded-full bg-emerald-400 shadow-[0_0_0_4px_rgba(52,211,153,.12)]',
  headerTitle: 'font-extrabold',
  headerActions: 'flex items-center gap-1',
  iconBtn: 'inline-flex size-10 items-center justify-center rounded-xl text-zinc-300 transition hover:bg-white/10 hover:text-white',
  messagesArea: 'flex-1 space-y-3 overflow-y-auto bg-background p-4',
  message: 'flex',
  user: 'justify-end',
  assistant: 'justify-start',
  bubble: 'max-w-[86%] rounded-2xl border border-line bg-surface px-4 py-3 text-sm leading-6 shadow-sm [[class*="user"]_&]:border-brand-solid [[class*="user"]_&]:bg-brand-solid [[class*="user"]_&]:text-white',
  messageLink: 'font-bold text-brand underline underline-offset-4 [[class*="user"]_&]:text-white',
  typingBubble: 'inline-flex items-center gap-2',
  typingText: 'sr-only',
  typingDots: 'inline-flex gap-1 [&_span]:size-1.5 [&_span]:animate-pulse [&_span]:rounded-full [&_span]:bg-muted',
  welcomeMsg: 'rounded-2xl border border-line bg-surface p-4 text-sm leading-6 text-muted',
  suggestions: 'grid gap-2',
  suggestion: 'rounded-xl border border-line bg-surface px-3 py-2.5 text-left text-sm font-bold text-foreground transition hover:border-brand hover:bg-brand-soft focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand',
  error: 'flex items-center justify-between gap-3 rounded-2xl border border-red-400/40 bg-red-50 p-3 text-sm text-red-900 dark:bg-red-950/30 dark:text-red-100 [&_button]:inline-flex [&_button]:shrink-0 [&_button]:items-center [&_button]:gap-1.5 [&_button]:font-bold [&_button]:text-brand',
  inputArea: 'flex gap-2 border-t border-line bg-surface p-3',
  input: 'h-11 min-w-0 flex-1 rounded-xl border border-line bg-background px-3 text-sm text-foreground outline-none focus:border-brand focus:ring-4 focus:ring-red-500/10',
  sendBtn: 'inline-flex size-11 items-center justify-center rounded-xl bg-brand-solid text-white transition hover:bg-brand-solid-strong disabled:cursor-not-allowed disabled:opacity-40',
};

const contactAction =
  'inline-flex min-h-11 min-w-0 items-center justify-center gap-1.5 overflow-hidden rounded-xl px-2 text-[11px] font-extrabold text-white transition hover:-translate-y-0.5 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white min-[360px]:text-xs sm:gap-2 sm:px-3 sm:text-sm [&_span]:truncate';

export const contactModalStyles = {
  launcher: 'fixed bottom-[calc(18px+env(safe-area-inset-bottom))] right-[84px] z-[10000] inline-flex size-14 items-center justify-center rounded-full border border-white/20 bg-[#111114] text-white shadow-2xl shadow-black/30 transition hover:-translate-y-1 hover:bg-zinc-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand',
  backdrop: 'fixed inset-0 z-[10020] flex items-end justify-center bg-black/65 backdrop-blur-sm sm:items-center sm:p-6',
  modal: 'flex max-h-[92dvh] w-full max-w-[760px] flex-col overflow-hidden rounded-t-[28px] border border-line bg-surface-raised text-foreground shadow-2xl sm:max-h-[min(850px,90dvh)] sm:rounded-[28px]',
  header: 'flex items-start justify-between gap-4 border-b border-white/10 bg-[#111114] px-5 py-5 text-white sm:px-7 sm:py-6',
  eyebrow: 'mb-1 text-xs font-black tracking-[0.14em] text-red-300 uppercase',
  title: 'text-2xl font-black tracking-tight sm:text-3xl',
  subtitle: 'mt-2 max-w-2xl text-sm leading-6 text-zinc-300',
  close: 'inline-flex size-11 shrink-0 items-center justify-center rounded-xl border border-white/15 text-white transition hover:bg-white/10 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white',
  content: 'overflow-y-auto p-4 sm:p-6',
  sectionTitle: 'mb-3 text-lg font-black text-foreground',
  groups: 'grid gap-3 md:grid-cols-2',
  groupCard: 'rounded-2xl border border-line bg-surface p-4 shadow-sm',
  cityList: 'mb-4 flex flex-wrap gap-1.5',
  city: 'rounded-full border border-line bg-surface-raised px-2.5 py-1 text-xs font-bold text-muted',
  phone: 'mb-3 inline-flex min-h-11 items-center gap-2 text-lg font-black text-foreground transition hover:text-brand',
  groupActions: 'grid grid-cols-3 gap-2',
  callAction: `${contactAction} bg-blue-700 hover:bg-blue-800`,
  whatsappAction: `${contactAction} bg-green-800 hover:bg-green-900`,
  smsAction: `${contactAction} bg-indigo-700 hover:bg-indigo-800`,
  onlineSection: 'mt-5',
  onlineGrid: 'grid gap-2 sm:grid-cols-2',
  telegramAction: `${contactAction} bg-sky-800 hover:bg-sky-900`,
  emailAction: `${contactAction} min-w-0 bg-brand-solid hover:bg-brand-solid-strong`,
  socials: 'mt-2 grid grid-cols-3 gap-2 [&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center [&_a]:justify-center [&_a]:gap-2 [&_a]:rounded-xl [&_a]:border [&_a]:border-line [&_a]:bg-surface [&_a]:px-2 [&_a]:text-sm [&_a]:font-bold [&_a]:text-foreground [&_a]:transition [&_a:hover]:border-red-300/60 [&_a:hover]:bg-brand-soft',
  office: 'mt-5 flex flex-col gap-4 rounded-2xl border border-line bg-surface p-4 sm:flex-row sm:items-center sm:justify-between [&_p]:text-sm [&_p]:leading-6 [&_p]:text-muted',
  mapAction: 'inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl border border-line bg-surface-raised px-3 text-sm font-extrabold text-foreground transition hover:border-red-300/60 hover:bg-brand-soft',
  fullContacts: 'mt-4 flex min-h-12 items-center justify-center gap-2 rounded-xl border border-line bg-surface px-4 font-extrabold text-foreground transition hover:border-red-300/60 hover:bg-brand-soft hover:text-brand',
};

export const fleetDetailStyles = {
  container: 'text-foreground',
  mainTitle: 'mb-5 text-[clamp(1.8rem,4vw,3rem)] font-black tracking-tight',
  introSection: 'mb-6 rounded-2xl bg-brand-soft p-5',
  leadText: 'leading-7 text-muted',
  grid: 'grid gap-4 sm:grid-cols-2',
  article: 'rounded-2xl border border-line bg-surface p-5',
  sectionTitle: 'mb-3 text-xl font-extrabold',
  description: 'mb-3 leading-7 text-muted',
  fullDescription: 'mb-4 text-sm leading-6 text-muted',
  factsList: 'grid gap-3 border-t border-line pt-4',
  factLabel: 'block text-xs font-black tracking-wide text-brand uppercase',
  factValue: 'mt-1 block text-sm leading-6 text-foreground',
  divider: 'my-7 h-px bg-line',
  importantSection: 'rounded-2xl border border-amber-400/30 bg-amber-50 p-5 dark:bg-amber-950/20',
  noticeTitle: 'mb-2 text-xl font-extrabold text-amber-950 dark:text-amber-100',
  noticeText: 'leading-7 text-amber-900 dark:text-amber-200',
  fleetList: 'mt-3 leading-7 text-amber-900 dark:text-amber-200',
  guarantees: 'mt-6 rounded-2xl border border-line bg-surface p-5',
  guaranteesTitle: 'mb-3 text-xl font-extrabold',
  guaranteesList: 'grid gap-2 text-muted [&_li]:before:mr-2 [&_li]:before:text-brand [&_li]:before:content-["✓"]',
};

export const fleetOfferStyles = {
  wrapper: 'mx-auto my-12 grid max-w-[1400px] gap-6 rounded-[32px] border border-line bg-surface p-5 shadow-soft sm:p-9 lg:grid-cols-[.85fr_1.15fr]',
  left: 'flex flex-col justify-center',
  badge: 'mb-4 w-fit rounded-full bg-brand-soft px-3 py-1 text-xs font-black tracking-wider text-brand uppercase',
  title: 'text-[clamp(2rem,4vw,3.6rem)] font-black leading-[1.04] tracking-[-0.04em] text-foreground',
  description: 'mt-5 grid gap-3',
  text: 'leading-7 text-muted',
  actions: 'mt-7 flex flex-wrap gap-3',
  primary: `${buttonBase} border-0 bg-brand-solid text-white hover:bg-brand-solid-strong`,
  secondary: `${buttonBase} border border-line bg-surface-raised text-foreground hover:bg-brand-soft`,
  right: 'grid gap-4 sm:grid-cols-2',
  card: 'rounded-2xl border border-line bg-surface-raised p-5 shadow-sm [&_h3]:mb-2 [&_h3]:text-lg [&_h3]:font-extrabold [&_p]:leading-6 [&_p]:text-muted',
  detailsBtn: 'mt-4 inline-flex min-h-11 items-center font-bold text-brand underline underline-offset-4',
  notice: 'rounded-2xl border border-red-300/30 bg-brand-soft p-5 sm:col-span-2 [&_h4]:mb-2 [&_h4]:font-extrabold [&_p]:leading-6 [&_p]:text-muted',
  loaderPlaceholder: 'h-48 animate-pulse rounded-2xl bg-line',
};

export const offerDetailsStyles = {
  detailsContent: 'text-foreground',
  detailsTitle: 'mb-4 text-3xl font-black tracking-tight',
  detailsText: 'grid gap-5',
  detailsDescription: 'leading-7 text-muted',
  detailsList: 'grid gap-3 text-foreground [&_li]:flex [&_li]:items-start [&_li]:gap-3',
  checkIcon: 'inline-flex size-6 shrink-0 items-center justify-center rounded-full bg-brand-soft font-black text-brand',
  detailsBtn: '',
};

export const tiktokStyles = {
  section: 'mx-auto max-w-[1400px] px-4 py-12 text-foreground sm:px-6 sm:py-20',
  header: 'mb-7',
  title: 'text-[clamp(2rem,4vw,3.4rem)] font-black tracking-tight',
  subtitle: 'mt-3 max-w-2xl leading-7 text-muted',
  sliderWrapper: 'relative',
  grid: 'flex snap-x snap-mandatory gap-4 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  videoWrapper: 'min-w-[84%] snap-start overflow-hidden rounded-3xl border border-line bg-surface p-3 shadow-soft sm:min-w-[45%] lg:min-w-[31%]',
  videoPlaceholder: 'min-h-[500px] overflow-hidden rounded-2xl bg-zinc-950',
  navBtn: 'absolute top-1/2 z-10 hidden size-12 -translate-y-1/2 items-center justify-center rounded-full bg-black/75 text-3xl text-white shadow-xl transition hover:bg-brand-solid disabled:opacity-30 sm:flex',
  prev: '-left-4',
  next: '-right-4',
  controls: 'mt-5 flex justify-center gap-1',
  dot: 'size-11 rounded-full before:mx-auto before:block before:size-2.5 before:rounded-full before:bg-zinc-400 before:content-[""]',
  activeDot: 'before:scale-125 before:bg-brand',
  videoPlaceholderUnused: '',
};

export const carContentStyles = {
  guide: 'bg-background py-12 text-foreground sm:py-20',
  container: 'mx-auto max-w-[1200px] px-4 sm:px-6',
  header: 'mb-8 rounded-3xl border border-line bg-surface p-6 shadow-soft sm:p-9 [&_h2]:text-[clamp(1.8rem,4vw,3rem)] [&_h2]:font-black [&_p]:mt-3 [&_p]:leading-7 [&_p]:text-muted',
  eyebrow: 'mb-3 text-xs font-black tracking-wider text-brand uppercase',
  grid: 'grid gap-4 sm:grid-cols-2 [&_article]:rounded-2xl [&_article]:border [&_article]:border-line [&_article]:bg-surface [&_article]:p-5 [&_article_h3]:mb-3 [&_article_h3]:text-xl [&_article_h3]:font-extrabold [&_article_p]:leading-7 [&_article_p]:text-muted',
  process: 'mt-8 rounded-3xl border border-line bg-surface p-6 shadow-soft sm:p-9 [&_h2]:mb-5 [&_h2]:text-2xl [&_h2]:font-black [&_ol]:grid [&_ol]:gap-3 [&_li]:text-muted',
  comparison: 'mt-8 rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-8 [&_h2]:mb-5 [&_h2]:text-2xl [&_h2]:font-black',
  coverage: 'mt-8 rounded-3xl border border-line bg-surface p-6 shadow-soft sm:p-9 [&_h2]:mb-4 [&_h2]:text-2xl [&_h2]:font-black [&_p]:leading-7 [&_p]:text-muted',
  tableWrap: 'overflow-x-auto rounded-2xl border border-line [&_table]:w-full [&_th]:bg-brand-soft [&_th]:p-3 [&_th]:text-left [&_th]:text-sm [&_td]:border-t [&_td]:border-line [&_td]:p-3 [&_td]:text-sm [&_td]:text-muted',
};

export const carDetailStyles = {
  container: 'min-h-screen bg-background pb-16 text-foreground',
  header: 'mx-auto max-w-[1200px] px-5 pb-6 pt-8',
  carName: 'text-[clamp(2rem,5vw,4rem)] font-black tracking-[-0.045em]',
  carYear: 'mt-2 text-lg text-muted',
  grid: 'mx-auto grid max-w-[1200px] gap-6 px-5 lg:grid-cols-[1.05fr_.95fr]',
  imageGallery: 'rounded-3xl border border-line bg-surface p-3 shadow-soft outline-none focus-visible:ring-2 focus-visible:ring-brand',
  galleryStage: 'relative aspect-[4/3] overflow-hidden rounded-[20px] bg-zinc-100 dark:bg-zinc-900',
  galleryImage: 'object-cover',
  galleryImageDetailLeft: 'origin-left scale-[1.3] object-cover',
  galleryImageDetailRight: 'origin-right scale-[1.3] object-cover',
  galleryCounter: 'absolute right-3 top-3 z-10 rounded-full bg-black/70 px-3 py-1 text-xs font-extrabold text-white backdrop-blur',
  galleryNav: 'absolute top-1/2 z-10 flex size-11 -translate-y-1/2 items-center justify-center rounded-full border border-white/20 bg-black/70 text-white shadow-lg backdrop-blur transition hover:bg-brand-solid focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white',
  galleryPrev: 'left-3',
  galleryNext: 'right-3',
  galleryThumbs: 'mt-3 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
  galleryThumb: 'relative aspect-[4/3] w-24 shrink-0 overflow-hidden rounded-xl border-2 border-transparent bg-zinc-100 transition hover:border-red-300 focus-visible:outline-2 focus-visible:outline-brand dark:bg-zinc-900',
  galleryThumbActive: 'border-brand',
  galleryThumbImage: 'object-cover',
  galleryThumbDetailLeft: 'origin-left scale-[1.3] object-cover',
  galleryThumbDetailRight: 'origin-right scale-[1.3] object-cover',
  details: 'grid gap-5',
  detailsGroup: 'rounded-3xl border border-line bg-surface p-5 shadow-soft sm:p-7',
  detailsTitle: 'mb-4 text-2xl font-black tracking-tight',
  specList: 'grid gap-3 [&_li]:flex [&_li]:flex-wrap [&_li]:items-start [&_li]:justify-between [&_li]:gap-3 [&_li]:border-b [&_li]:border-line [&_li]:pb-3 [&_li]:text-muted [&_li_span]:font-bold [&_li_span]:text-foreground',
  icon: 'mr-2 inline text-brand',
  priceRow: 'relative',
  priceNote: 'w-full text-xs leading-5 text-muted',
  categories: '',
  categoryTag: '',
  infoSection: 'mx-auto mt-8 grid max-w-[1200px] gap-5 px-5 lg:grid-cols-2',
  infoBlock: 'rounded-3xl border border-line bg-surface p-6 shadow-soft lg:col-span-2',
  noticeBlock: 'rounded-3xl border border-amber-400/30 bg-amber-50 p-6 dark:bg-amber-950/20',
  seoBlock: 'rounded-3xl border border-line bg-surface p-6 shadow-soft',
  infoEyebrow: 'mb-2 text-xs font-black tracking-wider text-brand uppercase',
  infoTitle: 'mb-3 text-2xl font-black tracking-tight',
  noticeTitle: 'mb-3 text-xl font-black text-amber-950 dark:text-amber-100',
  infoText: 'leading-7 text-muted',
  noticeText: 'leading-7 text-amber-900 dark:text-amber-200',
  notFound: 'mx-auto max-w-2xl p-8 text-center',
};
